import{S as v,i as l,a as m}from"./assets/vendor-c145bea9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&n(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const L=document.querySelector(".form"),u=document.querySelector(".gallery");document.querySelector(".gallery-box");const c=document.querySelector(".loader-top"),f=document.querySelector(".loader-bottom");document.querySelector("input");const a=document.querySelector(".load-image");document.querySelector("body");let i=1,d="cat",p=40;const g=new v(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});L.addEventListener("submit",S);a.addEventListener("click",q);async function S(s){if(s.preventDefault(),c.style.display="block",a.style.display="none",i=1,d=s.target.elements.search.value.trim(),!d){u.innerHTML="",l.info({position:"topRight",message:"Error enter any symbols"}),c.style.display="none";return}try{const{data:{hits:r,totalHits:t}}=await h(d,i);if(r.length>0?(c.style.display="none",u.innerHTML=b(r),g.refresh(),l.success({position:"topRight",message:`We found ${t} photos`}),a.style.display="block"):(u.innerHTML="",l.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=p)return a.style.display="none",l.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})}catch{console.log("Error")}finally{c.style.display="none",s.target.reset()}}function h(s,r){return m.defaults.baseURL="https://pixabay.com",m.get("/api/",{params:{key:"41611095-6f6895f75fda0efc7328923df",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})}function b(s=[]){return s.reduce((r,t)=>r+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src =${t.webformatURL} alt=${t.tags}/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>Views: <span class="text-value">${t.views}</span></p>
          <p>Comments: <span class="text-value">${t.comments}</span></p>
          <p>Downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){f.style.display="block",a.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{i+=1;const{data:{hits:n,totalHits:e}}=await h(d,i),o=Math.ceil(e/p);if(a.style.display="block",u.insertAdjacentHTML("beforeend",b(n)),g.refresh(),n.length<p||i>=o)return a.style.display="none",l.info({position:"bottomRight",message:"We're sorry, but you've reached the end of search results."})}catch(n){console.log(n)}finally{f.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
